# Generated by Django 3.1.7 on 2021-03-31 02:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_savings'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default=datetime.datetime(2021, 3, 31, 2, 23, 51, 284338, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.IntegerField(default=0),
        ),
    ]
